### ISSUE TITLE
Python 3.8 and incompatible CUDA drivers

### ISSUE THREAD

**Issue by KevinMusgrave** [conda/conda#9934]
## Current Behavior

In a python 3.8 environment, the following type of error occurs when installing two entirely separate packages:
```
The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```
You can see specifically what I mean in [this spyder-feedstock issue](https://github.com/conda-forge/spyder-feedstock/issues/72#issuecomment-581081100), and [this pytorch-metric-learning issue](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/55#issue-600601602). In both cases, users find that switching to python 3.7 fixes the problem. Also, here's a [stackoverflow question](https://stackoverflow.com/questions/61072464/anaconda-integration-with-cuda-9-0-shows-incompatible-package-error) in which the user has the same incompatible CUDA error when installing PyTorch.

This problem is difficult to debug because the error message says the CUDA driver is incompatible, even though the driver numbers match.

### Steps to Reproduce

In a python 3.8 environment:
```
conda install spyder
```
or
```
conda install pytorch-metric-learning
```

## Expected Behavior

The CUDA driver should be compatible, or the provided error message should be more informative.

## Environment Information
Here is an environment one user posted in the pytorch-metric-learning repo:
```
channels:
  - anaconda
  - conda-forge
  # - nodefaults
dependencies:
  - anaconda::flake8
  - anaconda::nb_conda
  - anaconda::notebook
  - anaconda::pandas
  - anaconda::pip
  - anaconda::pylint
  - anaconda::pytest
  - anaconda::python=3.8
  - conda-forge::black
  - conda-forge::jupyter_contrib_nbextensions
  - conda-forge::nb_black
  - nodejs
  - pip
```

**Comment by KevinMusgrave** [comment]
There was an error in the way I wrote the meta.yaml file. For any conda-building noobs out there, you can take a look at how I fixed my problem [here](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/55#issuecomment-629698723)
